-- Seed sample dynamic hero and lower promotional banners for development & testing
INSERT INTO banners (
    id, title, subtitle, description, position, color_theme, discount_text, cta_text,
    image_desktop_path, target_type, target_id, sort_order, is_active
) VALUES
(
    1,
    'Handcrafted Hair Accessories & Styling Essentials',
    'Silky Scrunchies, Velvet Bows & Pearl Claws',
    'Upgrade your hair styling with anti-breakage pure satin scrunchies, French claw clips, and chic aesthetic barrettes designed for all hair types.',
    'HOME_HERO',
    'purple',
    'FLAT 50% OFF',
    'Explore Hair Styling →',
    'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    1,
    1,
    1
),
(
    2,
    'Korean Dainty Jewellery & Minimalist Chains',
    'Water-Resistant, Anti-Tarnish & Hypoallergenic',
    'Delicate zircon butterfly pendants, sparkling crystal drop earrings, and stackable charm bracelets crafted for effortless daily elegance.',
    'HOME_HERO',
    'blue',
    'UP TO 55% OFF',
    'Shop Jewellery Collection →',
    'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    2,
    2,
    1
),
(
    3,
    'Personalized Gift Hampers & Pamper Boxes',
    'The Most Thoughtful Present for Loved Ones',
    'Aromatherapy soy candles, artisan ceramic mugs, plush teddy bears & skincare tools wrapped in luxury gold-foil gift packaging.',
    'HOME_HERO',
    'orange',
    'EXTRA 20% OFF',
    'Discover Gift Hampers →',
    'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    8,
    3,
    1
),
(
    4,
    'Cute Pastel Teddy Bears & STEM Creative Blocks',
    'Safe, Huggable & Wonderfully Crafted',
    'Baby-safe non-toxic velvet plushies and 3D magnetic building construction tiles that spark endless imagination and joy.',
    'HOME_HERO',
    'lavender',
    '100% CHILD SAFE',
    'Browse Toys & Fun →',
    'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    4,
    4,
    1
),
(
    5,
    'Curated Luxury Gift Hampers & Festive Combos',
    'Artisan Mugs, Candles & Pamper Gift Sets',
    'Celebrate birthdays and milestones with bespoke luxury hampers wrapped in designer ribbons.',
    'HOME_MIDDLE',
    'purple',
    'EXTRA 20% OFF',
    'Shop Hampers →',
    'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    8,
    1,
    1
),
(
    6,
    'Travel Cosmetic Pouches & Vanity Cases',
    'Water-Resistant Quilted Velvet & Golden Zipper',
    'Keep your makeup, skincare bottles and brushes cleanly organized on the go.',
    'HOME_MIDDLE',
    'pink',
    'FLAT 40% OFF',
    'Explore Pouches →',
    'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    5,
    2,
    1
),
(
    7,
    'Anti-Tarnish Daily Wear Jewellery Stack',
    '18K Gold Plated Butterfly Chains & Huggie Hoops',
    'Hypoallergenic zircon pendants and delicate layered bracelets for elegant styling.',
    'HOME_MIDDLE',
    'blue',
    'BUY 2 GET 10% OFF',
    'View Jewellery →',
    'https://images.unsplash.com/photo-1611591475152-4732a1ad3294?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    2,
    3,
    1
),
(
    8,
    'Cute Velvet Plush Toys & Creative Blocks',
    'Baby-Safe Non-Toxic Cotton & STEM Fun',
    'Super huggable 35cm pastel teddy bears and 3D magnetic tiles for endless laughter.',
    'HOME_MIDDLE',
    'orange',
    'STARTING ₹399',
    'Browse Toys →',
    'https://images.unsplash.com/photo-1558877385-81a1c7e67d72?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    4,
    4,
    1
),
(
    9,
    'Free Express Delivery on Orders Above ₹499',
    'Same-Day Dispatch & Easy 7-Day Returns',
    'Shop across all supermarket categories and enjoy seamless door-to-door delivery.',
    'HOME_MIDDLE',
    'teal',
    'FREE SHIPPING',
    'Start Shopping →',
    'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    'CATEGORY',
    1,
    5,
    1
)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    subtitle = VALUES(subtitle),
    description = VALUES(description),
    position = VALUES(position),
    color_theme = VALUES(color_theme),
    discount_text = VALUES(discount_text),
    cta_text = VALUES(cta_text),
    image_desktop_path = VALUES(image_desktop_path),
    target_type = VALUES(target_type),
    target_id = VALUES(target_id),
    sort_order = VALUES(sort_order),
    is_active = VALUES(is_active);
